force-app/main/default/objects/TT_Order_detail__c/TT_Order_detail__c.object-meta.xml
<CustomObject>
    <label>TT Order detail</label>
    <nameField>
        <label>Order detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TT Order details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TT_Order_detail__c/fields/TTCustomer__c.field-meta.xml
<CustomField>
    <fullName>TTCustomer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TTCustomer</label>
    <referenceTo>TTCustomer__c</referenceTo>
    <relationshipLabel>TT Order details</relationshipLabel>
    <relationshipName>TT_Order_details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TT_Order_detail__c/fields/TTOrder__c.field-meta.xml
<CustomField>
    <fullName>TTOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TTOrder</label>
    <referenceTo>TTOrder__c</referenceTo>
    <relationshipName>Order_details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TT_Order_detail__c/fields/TTProduct__c.field-meta.xml
<CustomField>
    <fullName>TTProduct__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TTProduct</label>
    <referenceTo>TTProduct__c</referenceTo>
    <relationshipName>Order_details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TTCustomer__c/TTCustomer__c.object-meta.xml
<CustomObject>
    <label>TTCustomer</label>
    <nameField>
        <label>TTCustomer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TTCustomers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TTOrder__c/TTOrder__c.object-meta.xml
<CustomObject>
    <label>TTOrder</label>
    <nameField>
        <label>TTOrder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TT Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TTOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Delivering</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TTOrder__c/fields/TTCustomer__c.field-meta.xml
<CustomField>
    <fullName>TTCustomer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TTCustomer</label>
    <referenceTo>TTCustomer__c</referenceTo>
    <relationshipLabel>TT Orders</relationshipLabel>
    <relationshipName>TT_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TTProduct__c/TTProduct__c.object-meta.xml
<CustomObject>
    <label>TTProduct</label>
    <nameField>
        <label>TTProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TTProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderClass.cls
public with sharing class OrderClass {
    @AuraEnabled(cacheable=true)
    public static TT_Order_detail__c newDetail (TTOrder__c order,TTProduct__c product,Integer quantity){
    
        TT_Order_detail__c newItem = new TT_Order_detail__c(TTOrder__r=order,TTProduct__r=product,Quantity__c= quantity);
        // newItem.TTOrder__c=item.TTOrder__c;
        //  newItem.TTProduct__c=item.TTProduct__c;
        //  newItem.Quantity__c= item.Quantity__c;
       return newItem;
   }

   public static insertDetail (List<TT_Order_detail__c> detail) {
    insert detail;
   }

   public static TTOrder__c  createOrder (TTCustomer__c customer){
    TTOrder__c newOrder = new TTOrder__c(Name='', TTCustomer__r=customer, Status__c='Paid');

    insert newOrder;

    return newOrder;
   }
}